### ISSUE TITLE
Error when run generate.py

### ISSUE THREAD

**Issue by Tsien** [MattVitelli/GRUV#11]
Error Info:
`Traceback (most recent call last):
  File "generate.py", line 62, in <module>
    max_seq_len = 10; #Defines how long the final song is. Total song length in samples = max_seq_len * example_len`
  
`File "/home/ubuntu/GRUV-master/gen_utils/sequence_generator.py", line 13, in generate_from_seed
    seedSeqNew = model._predict(seedSeq) #Step 1. Generate X_n + 1`
  
`File "build/bdist.linux-x86_64/egg/keras/backend/theano_backend.py", line 447, in __call__`

`AssertionError`

It looks like some TYPE issue. I am not familiar with python. Please help me out. Thanks!

**Comment by ianni67** [comment]
Getting the same error:
`ianni@goliath:~/PROGRAMMING/GRUV-master$ python generate.py

Using Theano backend.
/usr/local/lib/python2.7/dist-packages/theano/tensor/signal/downsample.py:5: UserWarning: downsample module has been moved to the pool module.
  warnings.warn("downsample module has been moved to the pool module.")
Loading training data
Finished loading training data
Starting generation!
Traceback (most recent call last):
  File "generate.py", line 59, in <module>
    sequence_length=max_seq_len, data_variance=X_var, data_mean=X_mean)
  File "/home/ianni/PROGRAMMING/GRUV-master/gen_utils/sequence_generator.py", line 13, in generate_from_seed
    seedSeqNew = model._predict(seedSeq) #Step 1. Generate X_n + 1
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/theano_backend.py", line 383, in __call__
    assert type(inputs) in {list, tuple}
AssertionError`

Please help

**Comment by anayebi** [comment]
GRUV currently supports only Keras v. 0.1.0, so I think your issue is being caused by using a higher version of Keras.
