### ISSUE TITLE
How to continue training process?

### ISSUE THREAD

**Issue by subzerofun** [MattVitelli/GRUV#27]
Let's say i've let the training process run for 12 hours and i'm currently at iteration 4000.
How do i continue training from the last saved file?

The default value of cur_iter in train.py is 0. But if i want to continue from my saved progress by setting cur_iter to 4000, the loss value is now at 1 again (where at the end of iteration 4000 it was at 0.54).

I've tried letting it run to iteration 8000 but the generated audio was worse than at iter. 4000 – it sounds as if the progress has been reset to the starting point (or worse).

So how do i correctly start the training again with from the last saved state?

---

BTW: What are good settings for epochs_per_iter and how much does increasing batch_size make a difference?

**Comment by albertocattani** [comment]
Hi,
Can I know how did you manage it?

**Comment by subzerofun** [comment]
Sorry, unfortunately – as you see – i didn't get an answer. And couldn't fix it myself.

This project is interesting to try out, but could be improved in a lot of areas. So it seems for now you need to watch your training results and when it reaches a point where the output sounds interesting just save it somewhere. If you start training again from scratch chances are high that you will get a completely different output.

**Comment by bgroenks96** [comment]
Don't expect to get very impressive results out of stock GRUV. You should try tweaking the model or maybe even reframing the problem on your own.

**Comment by albertocattani** [comment]
@bgroenks96 could you please explain to us the simplest way to restore a training process? Thank you very much!
