### ISSUE TITLE
generate.py : Wrong number of dimensions

### ISSUE THREAD

**Issue by piotch** [MattVitelli/GRUV#5]
Hello, 

I have the following env : 

Cython==0.23.4
h5py==2.5.0
Keras==0.3.0
numpy==1.10.1
PyYAML==3.11
scipy==0.16.1
six==1.10.0
Theano==0.7.0
wheel==0.24.0

I can run convert_directory.py and train.py as described in the README file, on either the mp3 provided or my own library.

But  when I run generate.py I have the following error : 

Using Theano backend.
Loading training data
Finished loading training data
Starting generation!
Traceback (most recent call last):
  File "generate.py", line 58, in <module>
    sequence_length=max_seq_len, data_variance=X_var, data_mean=X_mean)
  File "/Volumes/Data/tmp perso/gruv/GRUV/gen_utils/sequence_generator.py", line 13, in generate_from_seed
    seedSeqNew = model._predict(seedSeq) #Step 1. Generate X_n + 1
  File "/Users/---/.virtualenvs/gruv/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 357, in __call__
    return self.function(*inputs)
  File "/Users/---/.virtualenvs/gruv/lib/python2.7/site-packages/theano/compile/function_module.py", line 513, in __call__
    allow_downcast=s.allow_downcast)
  File "/Users/---/.virtualenvs/gruv/lib/python2.7/site-packages/theano/tensor/type.py", line 169, in filter
    data.shape))
TypeError: ('Bad input argument to theano function with name "/Users/---/.virtualenvs/gruv/lib/python2.7/site-packages/keras/backend/theano_backend.py:354"  at index 0(0-based)', 'Wrong number of dimensions: expected 3, got 2 with shape (40, 22050).')

**Comment by stuartlynn** [comment]
I have the same issue. Both convert and train run fine but predict gives the same error as @piotch 

Any ideas whats causing this?

**Comment by stuartlynn** [comment]
Just noticed that the model file was outputted as ```YourMusicLibraryNPWeights50``` instead of ```YourMusicLibraryNPWeights25``` which generate seems to expect as default. Not sure if thats related, changing ```cur_iter``` to 50 in the generate.py file lets it find the model but doesn't seem to help with the error.

**Comment by piotch** [comment]
Hello, 

indeed yes there is a small configuration problem in the repo : the training script is configured to do 50 iterations, and the generation script is set work with 25, but this is only a configuration issue. 

The error I reported happens after fixing the configuration and running train / generate with the same iteration setting.

Any ideas ?

Pierre

**Comment by iamthevastidledhitchhiker** [comment]
I'm running into the same problem.  Haven't found a solution yet.<br>
It seems this issue is similar to the one discussed here: fchollet/keras#90.
<br>However, the issue discussed in that thread stems from supplying a 3D tensor to 2D targets. In our case, the input is expected to be 3D tensors, but the one produced from our training set is 2D.

To restate the obvious: The solution involves identifying the source of the dimension mismatch in the input dataset (unless I'm completely wrong ¯\_(ツ)_/¯  ). I'm assuming the input is the training model. So either train.py is creating a training model without the correct dimensions or there's an issue with Keras backend. Or the files generated in convert_directory.py are causing this. Or it's something else.

I'll keep digging and update if I find a solution.

**Comment by stuartlynn** [comment]
Having poked about with the code a little, I found that changing model._predict to model.predict here : 

https://github.com/MattVitelli/GRUV/blob/master/gen_utils/sequence_generator.py#L13

lets the program run fine, but I am getting a sound file thats completely silent as an output. Looks like the difference in the methods are that predict takes the input, calls standardize_X on it then calls _predict_loop on the result which gets passed _predict. https://github.com/fchollet/keras/blob/master/keras/models.py#L560

Not sure if this helps at all. Going to keep playing to see if I can figure out what the difference is.

**Comment by anayebi** [comment]
I am not exactly sure about this issue either, but I do know that we used Keras version 0.1.0 when testing all this code, so perhaps using that version (rather than 0.3.0 as the OP seems to be using), will work for you as well. :)

**Comment by piotch** [comment]
Hello, 

thank you for the information I tried with Keras version 0.1.0 and generate.py worked. 
I have not yet looked into what changed in Keras could explain this.

**Comment by ianni67** [comment]
Hello,
thank you for the information. I confirm that with Keras version 0.1.0 the generate.py works.
However, there are several issues with 0.1.0, perhaps some are even affecting the performance of GRUV. In any case, I have a blocking issue with 0.1.0, related to some bugs it has, and really need to move to the latest version. 
Please, does anyone have a hint for fixing the compatibility issues between GRUV and latest versions of Keras?

**Comment by ianni67** [comment]
Just to let you know, I think I managed to make it work with the latest Keras.
Following the path marked by stuartlynn, I changed model._predict(seedSeq) to model.predict([seedSeq]) (**note the square brackets!**) here:
https://github.com/MattVitelli/GRUV/blob/master/gen_utils/sequence_generator.py#L13
and it worked plainly, producing the same result as when run with Keras 0.1.0.
Thank you all. I hope this will help.
